### ISSUE TITLE
How to switch to use microlib?

### ISSUE THREAD

**Issue by jmjoy** [ARM-software/vscode-keil-studio-pack#29]
I know this can be achieved through the following documentation:

https://developer.arm.com/documentation/dui0808/l/The-Arm-C-Micro-library/Building-an-application-with-microlib

But I can't find a way to add compile and link parameters.

**Comment by jkrech** [comment]
The CMSIS solution yaml format is documented here:
https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/YML-Input-Format.md
more specifically compiler specific `misc:` node is described here: 
https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/YML-Input-Format.md#misc

For a solution that only support AC6 in csolution.yml you can add
```
  compiler: AC6

  define: 
    - __MICROLIB
  define-asm:
    - __MICROLIB
  misc:
    - Link:
      - --library_type=microlib
```

Does that help?
